--- 
apiVersion: batch/v1
kind: Job
metadata: 
  name: r-sample-1
spec: 
  activeDeadlineSeconds: 18000
  completions: 1
  parallelism: 1
  template: 
    metadata: 
      name: r-sample-1
    spec: 
      containers: 
        - 
          args: 
            - master
            - 416538d158d9825ac9887950a5f1c62f7b44819b
            - "R/rscript.R"
            - r-jobs-input
            - r-jobs-output
          command: 
            - ./git_update_run.sh
          image: "gcr.io/gcp-experiments-185507/r"
          imagePullPolicy: IfNotPresent
          name: r-sampe-1
          resources: 
            limits: 
              cpu: 3
              memory: 2000Mi
            requests: 
              cpu: 3
              memory: 100Mi
      restartPolicy: Never
