--- 
apiVersion: batch/v1
kind: Job
metadata: 
  name: r-sample-
spec: 
  activeDeadlineSeconds: 18000
  completions: 1
  parallelism: 1
  template: 
    metadata: 
      name: r-sample-
    spec: 
      containers: 
        - 
          args: 
            - master
            - 266682c05b516ac88eb41576be8052b4d1074402
            - "R/rscript.R"
            - r-jobs-input
            - r-jobs-output
          command: 
            - ./git_update_run.sh
          image: "gcr.io/gcp-experiments-185507/r"
          imagePullPolicy: IfNotPresent
          name: r-sampe-3
          resources: 
            limits: 
              cpu: 1
              memory: 2000Mi
            requests: 
              cpu: 1
              memory: 100Mi
      restartPolicy: Never
